# Generated by Django 5.2.3 on 2025-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(help_text="The player's 64-bit Steam account ID.")),
                ('hero_id', models.IntegerField(help_text='The ID of the hero.')),
                ('score', models.FloatField(blank=True, help_text='Calculated performance score for the player-hero pair.', null=True)),
            ],
            options={
                'verbose_name': 'Hero Ranking',
                'verbose_name_plural': 'Hero Rankings',
                'db_table': 'hero_ranking',
                'indexes': [models.Index(fields=['hero_id', 'score'], name='hero_ranking_hero_id_score_idx')],
                'unique_together': {('account_id', 'hero_id')},
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('item', models.TextField(blank=True, help_text='Identifier for an item, if applicable.', null=True)),
                ('time', models.IntegerField(blank=True, help_text='Time bucket in minutes (e.g., 15 for 15-min mark).', null=True)),
                ('lane_role', models.SmallIntegerField(blank=True, help_text='Identifier for the lane role.', null=True)),
                ('epoch_week', models.IntegerField(blank=True, db_index=True, help_text='The ISO week (YYYYWW) for the data.', null=True)),
                ('games', models.BigIntegerField(default=1)),
                ('wins', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenarios',
                'constraints': [models.UniqueConstraint(fields=('hero_id', 'item', 'time', 'epoch_week'), name='scenarios_hero_item_time_week_unique'), models.UniqueConstraint(fields=('hero_id', 'lane_role', 'time', 'epoch_week'), name='scenarios_hero_lane_time_week_unique')],
            },
        ),
    ]
