# Generated by Django 5.2.3 on 2025-07-09 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('prefab', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('image_inventory', models.TextField(blank=True, null=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('item_rarity', models.TextField(blank=True, null=True)),
                ('item_type_name', models.TextField(blank=True, null=True)),
                ('used_by_heroes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cosmetic',
                'verbose_name_plural': 'Cosmetics',
                'db_table': 'cosmetics',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text="The hero's internal name, e.g., 'npc_dota_hero_antimage'.")),
                ('localized_name', models.TextField()),
                ('primary_attr', models.CharField(max_length=10)),
                ('attack_type', models.CharField(max_length=10)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
                'db_table': 'heroes',
                'ordering': ['localized_name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text="The item's internal name, e.g., 'item_blink'.")),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('secret_shop', models.BooleanField(default=False)),
                ('side_shop', models.BooleanField(default=False)),
                ('recipe', models.BooleanField(default=False)),
                ('localized_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['localized_name'],
            },
        ),
    ]
