# Generated by Django 5.2.3 on 2025-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ticket', models.CharField(blank=True, default='', max_length=255)),
                ('banner', models.URLField(blank=True, default='', max_length=255)),
                ('tier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'db_table': 'leagues',
                'ordering': ['-league_id'],
                'indexes': [models.Index(fields=['tier'], name='league_tier_idx')],
            },
        ),
    ]
