# Generated by Django 5.2.3 on 2025-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchstats_draft_timings'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teammatch',
            name='team_match_uniq',
        ),
        migrations.AddConstraint(
            model_name='teammatch',
            constraint=models.UniqueConstraint(fields=('team', 'match'), name='uniq_team_match'),
        ),
    ]
