# Generated by Django 5.2.3 on 2025-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='draft_timings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
